### ISSUE TITLE
In Cadence, if PyQt4 is not installed LV2_PATH is set to empty

### ISSUE THREAD

**Issue by ycollet** [falkTX/Cadence#101]
I installed Cadence on fedora 21 64 bits from git repo.
PyQt4 was not installed on my system.
When I started qtractor, it was not able to locate LV2 plugins because LV2_PATH was set to empty at startup by the script data/21cadence-session-inject.

The command "$INSTALL_PREFIX/bin/cadence-session-start --printLADSPA_PATH" in the script 21cadence-session-inject hangs with a message related to missing PyQt4 python package and then LV2_PATH is set to empty (and the same happens for the other environment variables).

**Comment by falkTX** [comment]
> I installed Cadence on fedora 21 64 bits from git repo.
> PyQt4 was not installed on my system.

That's the problem, how did you build and install cadence without having PyQt4 in the first place?

**Comment by ycollet** [comment]
Everything seems to compile fine. I installed Cadence in a specific directory: /local/stow/cadence-devel.

Some compilation statements:

/usr/lib64/qt4/bin/moc ../widgets/pixmapkeyboard.hpp -o ../widgets/moc_pixmapkeyboard.cpp                                                                               
g++ -c xycontroller.cpp -O2 -ffast-math -mtune=generic -msse -mfpmath=sse -Wall -Wextra -DNDEBUG -std=c++0x  -DQT_NO_DEBUG -DQT_NO_DEBUG_STREAM -DQT_NO_DEBUG_OUTPUT -I../widgets -DQT_SHARED -I/usr/include/QtGui -I/usr/include/QtCore  -o xycontroller.o                                                                                     
g++ -c qrc_resources-xycontroller.cpp -O2 -ffast-math -mtune=generic -msse -mfpmath=sse -Wall -Wextra -DNDEBUG -std=c++0x  -DQT_NO_DEBUG -DQT_NO_DEBUG_STREAM -DQT_NO_DEBUG_OUTPUT -I../widgets -DQT_SHARED -I/usr/include/QtGui -I/usr/include/QtCore  -o qrc_resources-xycontroller.o
g++ -c ../widgets/pixmapdial.cpp -O2 -ffast-math -mtune=generic -msse -mfpmath=sse -Wall -Wextra -DNDEBUG -std=c++0x  -DQT_NO_DEBUG -DQT_NO_DEBUG_STREAM -DQT_NO_DEBUG_OUTPUT -I../widgets -DQT_SHARED -I/usr/include/QtGui -I/usr/include/QtCore  -o ../widgets/pixmapdial.o
g++ -c ../widgets/pixmapkeyboard.cpp -O2 -ffast-math -mtune=generic -msse -mfpmath=sse -Wall -Wextra -DNDEBUG -std=c++0x  -DQT_NO_DEBUG -DQT_NO_DEBUG_STREAM -DQT_NO_DEBUG_OUTPUT -I../widgets -DQT_SHARED -I/usr/include/QtGui -I/usr/include/QtCore  -o ../widgets/pixmapkeyboard.o
g++ -c ../widgets/moc_pixmapkeyboard.cpp -O2 -ffast-math -mtune=generic -msse -mfpmath=sse -Wall -Wextra -DNDEBUG -std=c++0x  -DQT_NO_DEBUG -DQT_NO_DEBUG_STREAM -DQT_NO_DEBUG_OUTPUT -I../widgets -DQT_SHARED -I/usr/include/QtGui -I/usr/include/QtCore  -o ../widgets/moc_pixmapkeyboard.o
g++ xycontroller.o qrc_resources-xycontroller.o ../widgets/pixmapdial.o ../widgets/pixmapkeyboard.o ../widgets/moc_pixmapkeyboard.o  -lQtGui -lQtCore  -ldl -o cadence-xycontroller && strip cadence-xycontroller
make[1]: Leaving directory '/home/collette/repositories/Cadence/c++/xycontroller'
pyrcc4 -py3 resources/resources.qrc -o src/resources_rc.py
pyuic4 resources/ui/cadence.ui -o src/ui_cadence.py
pyuic4 resources/ui/cadence_tb_jack.ui -o src/ui_cadence_tb_jack.py
pyuic4 resources/ui/cadence_tb_alsa.ui -o src/ui_cadence_tb_alsa.py
pyuic4 resources/ui/cadence_tb_a2j.ui -o src/ui_cadence_tb_a2j.py
pyuic4 resources/ui/cadence_tb_pa.ui -o src/ui_cadence_tb_pa.py
pyuic4 resources/ui/cadence_rwait.ui -o src/ui_cadence_rwait.py
pyuic4 resources/ui/catarina.ui -o src/ui_catarina.py
pyuic4 resources/ui/catarina_addgroup.ui -o src/ui_catarina_addgroup.py
pyuic4 resources/ui/catarina_removegroup.ui -o src/ui_catarina_removegroup.py
pyuic4 resources/ui/catarina_renamegroup.ui -o src/ui_catarina_renamegroup.py
pyuic4 resources/ui/catarina_addport.ui -o src/ui_catarina_addport.py
pyuic4 resources/ui/catarina_removeport.ui -o src/ui_catarina_removeport.py
pyuic4 resources/ui/catarina_renameport.ui -o src/ui_catarina_renameport.py
pyuic4 resources/ui/catarina_connectports.ui -o src/ui_catarina_connectports.py
pyuic4 resources/ui/catarina_disconnectports.ui -o src/ui_catarina_disconnectports.py
pyuic4 resources/ui/catia.ui -o src/ui_catia.py
pyuic4 resources/ui/claudia.ui -o src/ui_claudia.py
pyuic4 resources/ui/claudia_studioname.ui -o src/ui_claudia_studioname.py
pyuic4 resources/ui/claudia_studiolist.ui -o src/ui_claudia_studiolist.py
pyuic4 resources/ui/claudia_createroom.ui -o src/ui_claudia_createroom.py
pyuic4 resources/ui/claudia_projectname.ui -o src/ui_claudia_projectname.py
pyuic4 resources/ui/claudia_projectproperties.ui -o src/ui_claudia_projectproperties.py
pyuic4 resources/ui/claudia_runcustom.ui -o src/ui_claudia_runcustom.py
pyuic4 resources/ui/claudia_launcher.ui -o src/ui_claudia_launcher.py
pyuic4 resources/ui/claudia_launcher_app.ui -o src/ui_claudia_launcher_app.py
pyuic4 resources/ui/logs.ui -o src/ui_logs.py
pyuic4 resources/ui/render.ui -o src/ui_render.py
pyuic4 resources/ui/settings_app.ui -o src/ui_settings_app.py
pyuic4 resources/ui/settings_jack.ui -o src/ui_settings_jack.py


And the result of the problematic command:

 /local/stow/cadence-devel/bin/cadence-session-start --printLADSPA_PATH
Traceback (most recent call last):
  File "/local/stow/cadence-devel/share/cadence/src/cadence_session_start.py", line 6, in <module>
    from PyQt4.QtCore import QCoreApplication
ImportError: No module named 'PyQt4'

**Comment by ycollet** [comment]
PyQt4 is installed on my system.

**Comment by falkTX** [comment]
Well, that's not what the cadence-session-start script seems to indicate.

**Comment by ycollet** [comment]
On my system, I tested a really small example:

Python 2.7.8 (default, Apr 15 2015, 09:26:43) 
[GCC 4.9.2 20150212 (Red Hat 4.9.2-6)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import PyQt4
>>> 
>>> from PyQt4.QtCore import QCoreApplication
>>>

Seems to work fine.
I

**Comment by ycollet** [comment]
OK, I installed only PyQt4 for python-2.7.
PyQt4 is not installed for python3. And in the cadence-session-start script, first, if python3 is installed, then python3 is used. And the presence of PyQt4 is not checked.

**Comment by falkTX** [comment]
Cadence uses python3, not python2.
Install PyQt4 for python3 and Cadence will work right.

**Comment by ycollet** [comment]
Cadence seems to use python3 if python3 is installed and then if python3 is not installed, it uses the default python.

**Comment by falkTX** [comment]
That's because on some distros there's no /usr/bin/python3, only /usr/bin/python.
