### ISSUE TITLE
Building from source Centos7

### ISSUE THREAD

**Issue by lorddrachenblut** [falkTX/Cadence#103]
I've managed to build Cadence from source successfully on CentOS 7 but when I go to run it I get this error

cadence
Traceback (most recent call last):
  File "/usr/local/share/cadence/src/cadence.py", line 23, in <module>
    from PyQt4.QtCore import QFileSystemWatcher, QThread
ImportError: No module named 'PyQt4'

any suggestions on how to resolve this would be greatly appreciated.

**Comment by falkTX** [comment]
I saw that before.

you need python3-pyqt4, not python2.

**Comment by lorddrachenblut** [comment]
I'll double check that.  Thanks for the suggestion.

I tried the prebuilt binary and it seemed to start just fine

**Comment by lorddrachenblut** [comment]
Just as an update that package doesn't exist for CentOS 7, or any version of CentOS as far as I can tell

**Comment by falkTX** [comment]
If you don't have python3-pyqt4 package there's nothing I can do.
FYI Sometime later Cadence will move to Qt5.

I suggest you to move to a newer distro.

**Comment by lorddrachenblut** [comment]
CentOS 7 is less than a year old I believe at this point.  

What's unhelpful is installing python3's qt4 package via python3-pip doesn't work
