### ISSUE TITLE
Cadence - KDE5 integration

### ISSUE THREAD

**Issue by daeavelwyn** [falkTX/Cadence#104]
Hi folks,

Just want to mention an issue integration In the screenshot below, the bridge is enable and running, but the start button isn't silver light, it's still black. The same for the midi bridge.
I'm using kubuntu 15.04 with plasma 5.2.2 and QT 5.4.1. I'm using the default breeze theme from official kde release.

![cadence_kde5-integration](https://cloud.githubusercontent.com/assets/4292225/8397215/221f9d44-1dc4-11e5-801b-9c6474b1c8d9.png)

**Comment by falkTX** [comment]
this has nothing to do with cadence.
cadence doesn't control the qt4 theme.

you need to report the bug against something else.
not exactly sure what...
