### ISSUE TITLE
[bug] cadence-session-start

### ISSUE THREAD

**Issue by stemuedendron** [falkTX/Cadence#107]
cadence-session-start does not work with parameter --maybe-system-start.

line 23:
```shell
if [ "$CADENCE_AUTO_STARTED"x == ""x ]; then
```
should be:
```shell
if [ "$CADENCE_AUTO_STARTED"x == "true"x ]; then
```

**Comment by falkTX** [comment]
That's not right.

the code is testing wherever the 21cadence-session-inject file actually did anything or not, and only starting jack if the 1st attempt was skipped (as it happens on some DEs).
if the 1st attempt failed then we need to figure out why.

**Comment by stemuedendron** [comment]
Ok, my fault.
That means 21cadence-session-inject sets $CADENCE_AUTO_STARTED to true but did not start jack. I can check after X start:
```shell
echo $CADENCE_AUTO_STARTED
```
and get 'true'. But jack is not running.

**Comment by stemuedendron** [comment]
Ok. So I look in 21cadence-session-inject:
```shell
# Cadence Session Startup Injection
# Set plugin paths and start JACK (or not) according to user settings

INSTALL_PREFIX="X-PREFIX-X"

if [ -f $INSTALL_PREFIX/bin/cadence-session-start ]; then

export CADENCE_AUTO_STARTED="true"

export LADSPA_PATH="`$INSTALL_PREFIX/bin/cadence-session-start --printLADSPA_PATH`"
export DSSI_PATH="`$INSTALL_PREFIX/bin/cadence-session-start --printDSSI_PATH`"
export LV2_PATH="`$INSTALL_PREFIX/bin/cadence-session-start --printLV2_PATH`"
export VST_PATH="`$INSTALL_PREFIX/bin/cadence-session-start --printVST_PATH`"

STARTUP="$INSTALL_PREFIX/bin/cadence-session-start --system-start-by-x11-startup $STARTUP"

fi

unset INSTALL_PREFIX
```

As for as I see sets the line:
```shell
STARTUP="$INSTALL_PREFIX/bin/cadence-session-start --system-start-by-x11-startup $STARTUP"
```
the value of $STARTUP. But where is $STARTUP executed?

**Comment by stemuedendron** [comment]
Sorry if I'm boring, but I understand now. $STARTUP is executed by XSession, on ubuntu by /etc/X11/Xsession.d/99x11-common_start
```shell
# $Id: 99x11-common_start 305 2005-07-03 18:51:43Z dnusinow $

# This file is sourced by Xsession(5), not executed.

exec $STARTUP

# vim:set ai et sts=2 sw=2 tw=80:
```

The problem is that on Ubuntu there is a script /etc/X11/Xsession.d/99upstart
```shell
# Start the user session
if [ -n "$UPSTART" ]; then
    case "$BASESESSION" in
        gnome-session*)
            export SESSIONTYPE=gnome-session
            ;;
        lxsession*)
            export SESSIONTYPE=lxsession
            ;;
    esac

    STARTUP="init --user"
    unset UPSTART
fi
```
As you see /etc/X11/Xsession.d/99upstart substitutes the value of STARTUP environment variable with "init --user".

**Comment by stemuedendron** [comment]
maybe this is helpful for understanding X startup on ubuntu:
http://askubuntu.com/questions/150487/what-happens-under-the-covers-to-log-me-in-and-start-up-unity-or-another-graphic

**Comment by stemuedendron** [comment]
Issus is solved with last update. Superb and thanks again!

**Comment by falkTX** [comment]
Thanks for testing!
