### ISSUE TITLE
Claudia knows about but doesn't save changes made in a client (Ardour4)

### ISSUE THREAD

**Issue by ebardie** [falkTX/Cadence#117]
When I remove Jack connexions via Ardour's UI, Claudia correctly detects the changes and displays them.

But Claudia doesn't save the new state.  I.e. when I restart the studio, the old connexions are still there.

If I make the same changes in Claudia, it does save them, and the removed connexions stay removed.

Claudia is installed from the 0.8.1+git20150903 package in the repo.

**Comment by falkTX** [comment]
That's precisely how ladish works.
Everytime you do a connection outside of ladish or claudia it will recognize it as an error (it was not done by the session manager) and ignore it.
You cannot use Ardour to manage connections while using ladish/claudia at the same time.
