### ISSUE TITLE
Show which device is being used in the cadence main status window

### ISSUE THREAD

**Issue by wolftune** [falkTX/Cadence#133]
I'd like to see, at a glance, which audio device is being used in the same view where I see the other general states (i.e. the main window for Cadence)

**Comment by falkTX** [comment]
I think there's already a request for this...
The answer sadly is that we have no current way to do this.

JACK can be started outside of cadence, and it does not have a way to report back the device selected when started, sadly.

**Comment by wolftune** [comment]
Oh yeah, damnit, sorry. Is there a good place to open issues for JACK itself?

**Comment by falkTX** [comment]
I don't think it's reason for closing this bug...

the right place to ask this would be jack itself yes.
currently we have ways to know the driver sample-rate, buffer-size and realtime on/off.
nothing more.

**Comment by wolftune** [comment]
If you want to reopen this, that's okay with me. Anyway, I opened https://github.com/jackaudio/jack2/issues/217
