### ISSUE TITLE
Simple question: Does one need pulseaudio-module-jack for pulseaudio routing?

### ISSUE THREAD

**Issue by basickarl** [falkTX/Cadence#137]
I can't seem to find information on this anywhere so I'll just ask straight out.

Do I need to install pulseaudio-module-jack to get pulseaudio working with jack when using cadence. I got the image that Cadence does this on it's own?

I'm running 14.04 otherwise.

**Comment by falkTX** [comment]
you do need it yes.
the includes the binary modules needed to activate it.

**Comment by basickarl** [comment]
Ok brilliant that was all for this question!
