### ISSUE TITLE
No module named "PyQt4" in Fedora 25 Beta, yet it's in lib64 directory

### ISSUE THREAD

**Issue by GraysonPeddie** [falkTX/Cadence#139]
Cadence is compiled successfully, yet I did get the message:

```
[grayson@htpc Cadence]$ cadence
Traceback (most recent call last):
  File "/usr/local/share/cadence/src/cadence.py", line 23, in <module>
    from PyQt4.QtCore import QFileSystemWatcher, QThread
ImportError: No module named 'PyQt4'
[grayson@htpc Cadence]$ locate pyqt4
/usr/lib64/qt4/plugins/designer/libpyqt4.so
```

Fedora 25 is in beta and is slated for release on November 15th, IIRC. Is there a possibility to get Cadence point towards the correct module?

I did read in #138 that you are moving from qt4 to qt5. Could that have something to do with the missing module?

**Comment by falkTX** [comment]
you're looking in the completely wrong place.
you need python3-qt4.

also cadence is not moving to qt5 anytime soon.

**Comment by GraysonPeddie** [comment]
My bad. Thanks.
