### ISSUE TITLE
g++  -mtune error

### ISSUE THREAD

**Issue by KC7NOA** [falkTX/Cadence#140]
odroid@odroid:~/Downloads/Cadence$ make
make -C c++/jackmeter
make[1]: Entering directory `/home/odroid/Downloads/Cadence/c++/jackmeter'
g++ -c jackmeter.cpp -O2 -ffast-math -mtune=generic -msse -mfpmath=sse -Wall -Wextra -DNDEBUG -std=c++0x  -DQT_NO_DEBUG -DQT_NO_DEBUG_STREAM -DQT_NO_DEBUG_OUTPUT -I../widgets -DQT_SHARED -I/usr/include/qt4 -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui   -o jackmeter.o
g++-4.8.real: error: unrecognized argument in option ‘-mtune=generic’
g++-4.8.real: note: valid arguments to ‘-mtune=’ are: arm1020e arm1020t arm1022e arm1026ej-s arm10e arm10tdmi arm1136j-s arm1136jf-s arm1156t2-s arm1156t2f-s arm1176jz-s arm1176jzf-s arm2 arm250 arm3 arm6 arm60 arm600 arm610 arm620 arm7 arm70 arm700 arm700i arm710 arm7100 arm710c arm710t arm720 arm720t arm740t arm7500 arm7500fe arm7d arm7di arm7dm arm7dmi arm7m arm7tdmi arm7tdmi-s arm8 arm810 arm9 arm920 arm920t arm922t arm926ej-s arm940t arm946e-s arm966e-s arm968e-s arm9e arm9tdmi cortex-a15 cortex-a5 cortex-a53 cortex-a7 cortex-a8 cortex-a9 cortex-m0 cortex-m0plus cortex-m1 cortex-m3 cortex-m4 cortex-r4 cortex-r4f cortex-r5 cortex-r7 ep9312 fa526 fa606te fa626 fa626te fa726te fmp626 generic-armv7-a iwmmxt iwmmxt2 marvell-pj4 mpcore mpcorenovfp native strongarm strongarm110 strongarm1100 strongarm1110 xscale
g++-4.8.real: error: unrecognized command line option ‘-msse’
g++-4.8.real: error: unrecognized command line option ‘-mfpmath=sse’
make[1]: *** [jackmeter.o] Error 1
make[1]: Leaving directory`/home/odroid/Downloads/Cadence/c++/jackmeter'
make: **\* [jackmeter] Error 2
odroid@odroid:~/Downloads/Cadence$ g++ --version
g++-4.8.real (Ubuntu/Linaro 4.8.4-2ubuntu1~14.04.3) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by KC7NOA** [comment]
im useing an cortex-a9

**Comment by falkTX** [comment]
This was handled some time ago
