### ISSUE TITLE
Cadence stop starting after updating Harfbuzz to 1.4.1

### ISSUE THREAD

**Issue by gvg100** [falkTX/Cadence#145]
This ticket just to submit a problem with harfbuzz preventing Cadence/Catia/Claudi to launch.

Ater updating my arch/manjaro box, Cadence doesn't launch anymore : it complains about a missing reference in libharfbuzz -> /usr/lib/libharfbuzz.so.0 : référence indéfinie vers « FT_Get_Var_Blend_Coordinates ».

I tried to compile from aur : same problem

-> Création d’une copie de travail du dépot Cadence git...
Clonage dans 'cadence-git'...
fait.
==> Lancement de pkgver()...
==> Version mise à jour : cadence-git 1:r990.92034ff-1
==> Lancement de build()...
make -C c++/jackmeter                                                                                           
make -C c++/xycontroller                                                                                        
pyrcc4 -py3 resources/resources.qrc -o src/resources_rc.py
pyuic4 resources/ui/cadence.ui -o src/ui_cadence.py
pyuic4 resources/ui/cadence_tb_jack.ui -o src/ui_cadence_tb_jack.py
pyuic4 resources/ui/cadence_tb_alsa.ui -o src/ui_cadence_tb_alsa.py
pyuic4 resources/ui/cadence_tb_a2j.ui -o src/ui_cadence_tb_a2j.py
make[1] : on entre dans le répertoire « /tmp/yaourt-tmp-vincent/aur-cadence-git/src/cadence-git/c++/xycontroller »
make[1] : on entre dans le répertoire « /tmp/yaourt-tmp-vincent/aur-cadence-git/src/cadence-git/c++/jackmeter »
pyuic4 resources/ui/cadence_tb_pa.ui -o src/ui_cadence_tb_pa.py
/usr/lib/qt4/bin/moc xycontroller.cpp -o xycontroller.moc
/usr/lib/qt4/bin/rcc -name resources-jackmeter ../../resources/resources-jackmeter.qrc -o qrc_resources-jackmeter.cpp
/usr/lib/qt4/bin/uic ../../resources/ui/xycontroller.ui -o ui_xycontroller.h
g++ -c jackmeter.cpp -O2 -ffast-math -mtune=generic -msse -mfpmath=sse -Wall -Wextra -DNDEBUG -std=c++0x -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DQT_NO_DEBUG -DQT_NO_DEBUG_STREAM -DQT_NO_DEBUG_OUTPUT -I../widgets -DQT_SHARED -I/usr/include/qt4 -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I/usr/include/qt4/QtCore -o jackmeter.o
/usr/lib/qt4/bin/rcc -name resources-xycontroller ../../resources/resources-xycontroller.qrc -o qrc_resources-xycontroller.cpp
/usr/lib/qt4/bin/moc ../widgets/pixmapkeyboard.hpp -o ../widgets/moc_pixmapkeyboard.cpp
g++ -c xycontroller.cpp -O2 -ffast-math -mtune=generic -msse -mfpmath=sse -Wall -Wextra -DNDEBUG -std=c++0x -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DQT_NO_DEBUG -DQT_NO_DEBUG_STREAM -DQT_NO_DEBUG_OUTPUT -I../widgets -DQT_SHARED -I/usr/include/qt4 -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I/usr/include/qt4/QtCore -o xycontroller.o
g++ -c qrc_resources-jackmeter.cpp -O2 -ffast-math -mtune=generic -msse -mfpmath=sse -Wall -Wextra -DNDEBUG -std=c++0x -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DQT_NO_DEBUG -DQT_NO_DEBUG_STREAM -DQT_NO_DEBUG_OUTPUT -I../widgets -DQT_SHARED -I/usr/include/qt4 -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I/usr/include/qt4/QtCore -o qrc_resources-jackmeter.o
g++ -c ../widgets/digitalpeakmeter.cpp -O2 -ffast-math -mtune=generic -msse -mfpmath=sse -Wall -Wextra -DNDEBUG -std=c++0x -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DQT_NO_DEBUG -DQT_NO_DEBUG_STREAM -DQT_NO_DEBUG_OUTPUT -I../widgets -DQT_SHARED -I/usr/include/qt4 -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I/usr/include/qt4/QtCore -o ../widgets/digitalpeakmeter.o
pyuic4 resources/ui/cadence_rwait.ui -o src/ui_cadence_rwait.py
g++ -c qrc_resources-xycontroller.cpp -O2 -ffast-math -mtune=generic -msse -mfpmath=sse -Wall -Wextra -DNDEBUG -std=c++0x -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DQT_NO_DEBUG -DQT_NO_DEBUG_STREAM -DQT_NO_DEBUG_OUTPUT -I../widgets -DQT_SHARED -I/usr/include/qt4 -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I/usr/include/qt4/QtCore -o qrc_resources-xycontroller.o
pyuic4 resources/ui/catarina.ui -o src/ui_catarina.py
pyuic4 resources/ui/catarina_addgroup.ui -o src/ui_catarina_addgroup.py
pyuic4 resources/ui/catarina_removegroup.ui -o src/ui_catarina_removegroup.py
pyuic4 resources/ui/catarina_renamegroup.ui -o src/ui_catarina_renamegroup.py
g++ jackmeter.o qrc_resources-jackmeter.o ../widgets/digitalpeakmeter.o -Wl,-O1,--sort-common,--as-needed,-z,relro -lQtGui -lQtCore -ldl -o cadence-jackmeter && strip cadence-jackmeter
pyuic4 resources/ui/catarina_addport.ui -o src/ui_catarina_addport.py
pyuic4 resources/ui/catarina_removeport.ui -o src/ui_catarina_removeport.py
g++ -c ../widgets/pixmapdial.cpp -O2 -ffast-math -mtune=generic -msse -mfpmath=sse -Wall -Wextra -DNDEBUG -std=c++0x -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DQT_NO_DEBUG -DQT_NO_DEBUG_STREAM -DQT_NO_DEBUG_OUTPUT -I../widgets -DQT_SHARED -I/usr/include/qt4 -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I/usr/include/qt4/QtCore -o ../widgets/pixmapdial.o
pyuic4 resources/ui/catarina_renameport.ui -o src/ui_catarina_renameport.py
pyuic4 resources/ui/catarina_connectports.ui -o src/ui_catarina_connectports.py
/usr/lib/libharfbuzz.so.0 : référence indéfinie vers « FT_Get_Var_Blend_Coordinates »
collect2: erreur : ld a retourné 1 code d'état d'exécution
make[1]: *** [Makefile:34: cadence-jackmeter] Error 1
make[1] : on quitte le répertoire « /tmp/yaourt-tmp-vincent/aur-cadence-git/src/cadence-git/c++/jackmeter »
make: *** [Makefile:31: jackmeter] Error 2
make: *** Attente des tâches non terminées....
g++ -c ../widgets/pixmapkeyboard.cpp -O2 -ffast-math -mtune=generic -msse -mfpmath=sse -Wall -Wextra -DNDEBUG -std=c++0x -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DQT_NO_DEBUG -DQT_NO_DEBUG_STREAM -DQT_NO_DEBUG_OUTPUT -I../widgets -DQT_SHARED -I/usr/include/qt4 -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I/usr/include/qt4/QtCore -o ../widgets/pixmapkeyboard.o
g++ -c ../widgets/moc_pixmapkeyboard.cpp -O2 -ffast-math -mtune=generic -msse -mfpmath=sse -Wall -Wextra -DNDEBUG -std=c++0x -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DQT_NO_DEBUG -DQT_NO_DEBUG_STREAM -DQT_NO_DEBUG_OUTPUT -I../widgets -DQT_SHARED -I/usr/include/qt4 -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I/usr/include/qt4/QtCore -o ../widgets/moc_pixmapkeyboard.o
g++ xycontroller.o qrc_resources-xycontroller.o ../widgets/pixmapdial.o ../widgets/pixmapkeyboard.o ../widgets/moc_pixmapkeyboard.o -Wl,-O1,--sort-common,--as-needed,-z,relro -lQtGui -lQtCore -ldl -o cadence-xycontroller && strip cadence-xycontroller
/usr/lib/libharfbuzz.so.0 : référence indéfinie vers « FT_Get_Var_Blend_Coordinates »
collect2: erreur : ld a retourné 1 code d'état d'exécution
make[1]: *** [Makefile:38: cadence-xycontroller] Error 1
make[1] : on quitte le répertoire « /tmp/yaourt-tmp-vincent/aur-cadence-git/src/cadence-git/c++/xycontroller »
make: *** [Makefile:34: xycontroller] Error 2
==> ERREUR : Une erreur s’est produite dans build().
    Abandon...
==> ERREUR : Makepkg n'a pas pu construire cadence-git.
==> Relancer la compilation de cadence-git ? [o/N]
==> ----------------------------------------------

I tried to compile Qjackctl from source 0.4.4 but it ended with the same problem so it don't seem to depend on Cadence code.

Hope it helps to track some bug.
Regards frome France.

**Comment by falkTX** [comment]
Seems like you need to rebuild some libs after that harfbuzz update.

**Comment by gvg100** [comment]
You are right! It was a freetype2 problem with plasma5 and harfbuzz 1.4.
I rebuild freetype with a newer version and everything is fine.
Sorry to have posted to quickly.
Thanks for your answers.
