### ISSUE TITLE
File format error with Render (workaround proposal)

### ISSUE THREAD

**Issue by bullk** [falkTX/Cadence#153]
Hello

thanks for your work on these usefull tools !

I use Cadence on Ubuntu Studio 64bits 16.04, on several computers, and I've an issue with Render :
wav files aren't correctly written (about data size), and several softwares don't want to open these files.
Audacity can, as it seems to "guess" what must be done.

So I browsed the code and I tried to launch jack_capture with same options as in render.py, and there was no problem.
I managed to reproduce the issue launching jack_capture in one terminal and sending SIGKILL with another one. No problem if sending SIGINT.

Then I dealed with render.py and QProcess, and found that if 
`self.fProcess.close()`
is replaced by
`self.fProcess.terminate()`
it works nice for me.

Can you look at this please?

Thanks

**Comment by falkTX** [comment]
Seems like a good suggestion, I'll change it now, thanks.
