### ISSUE TITLE
"command not found" if root is logged in before X is started

### ISSUE THREAD

**Issue by Gooberpatrol66** [falkTX/Cadence#180]
user: su
    root: su user
    user: startx
    user: cadence
    command not found

**Comment by falkTX** [comment]
hmm how is this a cadence issue?
likely $PATH is setup differently when run this way, and a bunch of other tools won't start either...

**Comment by Gooberpatrol66** [comment]
It happens even if I switch back before starting X.

**Comment by Gooberpatrol66** [comment]
Invalid
https://forums.gentoo.org/viewtopic-t-1074264-highlight-.html
