### ISSUE TITLE
[RFE] Autorun script when "kitchen" ready

### ISSUE THREAD

**Issue by t14462** [falkTX/Cadence#196]
When I login to session, I need unmute Headphones on front panel:
 amixer -c 0 set Headphone playback 100% unmute

...But Cadence override changes, and I need to launch my script manually again.

**Comment by falkTX** [comment]
cadence does no such thing, it never touches audio mixer.
something else on your desktop is doing that, certainly not cadence (and not jack either, as it also does not control volume).

**Comment by t14462** [comment]
So... I bridging Pulse->JACK->ALSA.
Perhaps something wrong with Pulse/KDE/systemd.
Something touches mixer in this combination.

OK, I'll search another info..
