### ISSUE TITLE
[Catia] Connect/Disconnect via CLI

### ISSUE THREAD

**Issue by Houkime** [falkTX/Cadence#201]
Wanted to automate jack ports connection the easy way (just by names) via Catia but Catia has no CLI.
Even simple connect-disconnect (port 1) (port 2) CLI would be nice.

**Comment by falkTX** [comment]
You can already do this with jack_(dis)connect tools. no need for catia here.

**Comment by Houkime** [comment]
Thanks)

**Comment by jebofponderworthy** [comment]
For more sophistication at the CLI, including saving and restoring
whole sets of connections, aj-snapshot works very well.
J.E.B.
On Sun, 2018-03-11 at 20:09 +0000, Houkime wrote:
> Wanted to automate jack ports connection the easy way (just by names)
> via Catia but Catia has no CLI.
> 
> Even simple connect-disconnect (port 1) (port 2) CLI would be nice.
> 
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 
> 
> 
>   
>   
> 
> 
> 
> 
> 
> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c5
> 5493e4bb","name":"GitHub"},"entity":{"external_key":"github/falkTX/Ca
> dence","title":"falkTX/Cadence","subtitle":"GitHub
> repository","main_image_url":"https://cloud.githubusercontent.com/ass
> ets/143418/17495839/a5054eac-5d88-11e6-95fc-
> 7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent
> .com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-
> b52498112777.png","action":{"name":"Open in GitHub","url":"https://gi
> thub.com/falkTX/Cadence"}},"updates":{"snippets":[{"icon":"DESCRIPTIO
> N","message":"[Catia] Connect/Disconnect CLI
> (#201)"}],"action":{"name":"View Issue","url":"https://github.com/fal
> kTX/Cadence/issues/201"}}}
-- 
Jonathan E. Brickman   jeb@ponderworthy.com   (785)233-9977
Hear us at ponderworthy.com -- CDs and MP3 now available!
Music of compassion; fire, and life!!!---
New Internet radio being built -- fireandliferadio.ponderworthy.com!!!!
