### ISSUE TITLE
Systray/tools Not Working

### ISSUE THREAD

**Issue by DancehallEcho** [falkTX/Cadence#209]
It's seems like "Tools" menu in the systray is not working. For exemple i can not launch Catia from there. But with previous version, Cadence was crashing when trying to launch Catia from the systray tool menu, so it's a little bit better lol

**Comment by trebmuh** [comment]
Confirmed that the links in systray -> Tools aren't working on a build from https://github.com/falkTX/Cadence/commit/7c6ca1026f3f4732f0a3d6f9e3d1827d6a797284 (Debian stretch up-to-date).

**Comment by trebmuh** [comment]
Fresh rebuild from https://github.com/falkTX/Cadence/commit/99b39989a010fae1acbce07af002b15e56a1d161 and it's all good now. Thanks falkTX !
