### ISSUE TITLE
Claudia fails to load special paths

### ISSUE THREAD

**Issue by falkTX** [falkTX/Cadence#220]
See https://linuxmusicians.com/viewtopic.php?f=4&t=18380&p=94600#p94600

**Comment by net147** [comment]
Caused by KDE - https://bugs.kde.org/show_bug.cgi?id=337491
It seems KDE is automatically adding alt shortcuts for the recent items menu by modifying the menu item text to add an ampersand so when Claudia reads back the text it has an ampersand added which messes up the path.
