### ISSUE TITLE
jackdbus not available

### ISSUE THREAD

**Issue by temrix** [falkTX/Cadence#251]
I am running Debian buster on a custom kernel and get 'jackdbus not available' when starting Cadence which I installed from the kx.studio-repos.

`jackd2` is not installed on the system, and I cannot get it to install correctly:
```
jackd2 : Depends on: libreadline6 (>= 6.0) is not installable
          Recommends: jackd2-firewire should not be installed
```

Is this a problem with the kx.studio-repo or a general problem in buster? How can I install JACK correctly?

**Comment by falkTX** [comment]
Did you install the gcc5 package for the repos?

**Comment by temrix** [comment]
No, that's why it did not work. Thank you!
