### ISSUE TITLE
Cadence cannot connect pulseaudio bridge

### ISSUE THREAD

**Issue by brandflake11** [falkTX/Cadence#253]
Hello all!
Running on an up to date Arch Linux, and this morning when trying to start my normal audio configuration of bridging pulseaudio into jack, I get this error with cadence:
```
PulseAudio is already running, bridge it...
Connection failure: Connection refused
pa_context_connect() failed: Connection refused
Connection failure: Connection refused
pa_context_connect() failed: Connection refused
Daemon not responding.
Daemon not responding.
Done
```

Does anyone know what might be going on? I suspect this is an issue with pulseaudio, since it just updated recently.

**Comment by falkTX** [comment]
Missing `pulseaudio-module-jack` package?

**Comment by brandflake11** [comment]
Hey falkTX,

This was just a problem with my Xfce session management. Sorry for the non existent issue!
