### ISSUE TITLE
Can't start JACK when switching to another user.

### ISSUE THREAD

**Issue by moonshaadow** [falkTX/Cadence#273]
_Ubuntu Studio 18.04.4 - Cadence_

It seems that Jack doesn't stop when I disconnect from an user. I can't start jack in another user because the sound card is unavailable.
I disconnect from 'user A' with jack server started, and then I connect to 'user B' and try to start jack via Cadence. Here's the log : 
```
Fri Feb  7 10:15:15 2020: Starting jack server...
Fri Feb  7 10:15:15 2020: JACK server starting in realtime mode with priority 10
Fri Feb  7 10:15:15 2020: self-connect-mode is "Don't restrict self connect requests"
Fri Feb  7 10:15:15 2020: ERROR: cannot open DB environment: Permission denied
Fri Feb  7 10:15:15 2020: Acquired audio card Audio0
Fri Feb  7 10:15:15 2020: creating alsa driver ... hw:PCH,0|hw:PCH,0|512|2|44100|0|0|nomon|swmeter|-|32bit
Fri Feb  7 10:15:15 2020: ERROR: 

ATTENTION: The playback device "hw:PCH,0" is already in use. Please stop the application using it and run JACK again
Fri Feb  7 10:15:15 2020: Released audio card Audio0
Fri Feb  7 10:15:15 2020: ERROR: Cannot initialize driver
Fri Feb  7 10:15:15 2020: ERROR: JackServer::Open failed with -1
Fri Feb  7 10:15:15 2020: ERROR: Failed to open server
```

**Comment by falkTX** [comment]
multi-user is not supported by cadence, and not straight forward to get working with jack.
I have no interest on it personally, so it is not something I will push towards.

UbuntuStudio have a tool that might work for this though.

**Comment by moonshaadow** [comment]
Ok, thanks. I 'm gonna looking for this tool :)

**Comment by moonshaadow** [comment]
This makes me use QjackCtl instead of Cadence, but I don't want. I don't really want to use multi-user anyway, it was just a temporary need. Thank's again for your fast answers.

**Comment by falkTX** [comment]
QjackCtl won't deal with multi-user and jack either, so it won't help you there.
JACK is not well suited for a multi-user scenario, very few people use it that way

**Comment by eeickmeyer** [comment]
The name of said tool is Ubuntu Studio Controls and only comes in 19.10 currently. Multi-user support is coming in 20.04 LTS and will be in our backports PPA for 18.04 and 19.10.

**Comment by moonshaadow** [comment]
QjackCtl has a feature to stop jack server when disconnecting from an user. But it needs qjackctl to be running. This way I can connect to another user without manually stop jack. I don't need multiple users running in the same time, I need to just change user sometimes.  So I just need jack to stop automatically when I disconnect.
