### ISSUE TITLE
Consider moving .log folder contents to .config

### ISSUE THREAD

**Issue by CadaverLab** [falkTX/Cadence#279]
Since folders such as `Cadence`, `falkTX`, `jack`, and `a2j` are already being created in `~/.config`, would it be possible to move the contents of the `~/.log` folder to one (or more) of the aforementioned ones? 
This would be in compliance with XDG_BASE_DIRS, thus decluttering `~` , and also centralize everything in one place

**Comment by falkTX** [comment]
The log contents are not created by Cadence, so nothing that we can do there.
You will have to request the individual projects (JACK, LADISH, A2J) to log their info in a new place.
