### ISSUE TITLE
Tray icon hover popup formating issue

### ISSUE THREAD

**Issue by AreYouLoco** [falkTX/Cadence#302]
When I hover the mouse over cadence icon some unformatted text is appearing as you can see on the screenshot attached.
I think bug is minor but still a bug.
![Screenshot from 2020-09-16 14-55-51](https://user-images.githubusercontent.com/6299176/93341228-1dc73500-f82e-11ea-92dd-bf2f39db7acc.png)
I am using cadence version 5:0.9.1 from kxrepos on Debian Bullseye with MATE desktop.

**Comment by vari-spec** [comment]
Same issue on Manjaro KDE 20, looking at the code looks like it never runs as KDE version, just Qt. Word wrap is working on manjaro so it isn't as ugly as the above but it's still unformatted rich text. I played around and fixed it for myself by removing the rich text in cadence.py updateSystrayTooltip() function by using \n for linebreaks but can't figure out how to get the rich text to be read.

**Comment by Marzal** [comment]
Same issue on ArchLinux KDE 5.20.2 / 5.75.0 / QT 5.15.1

I also didn't have any luck getting rich text on the [tooltip](https://github.com/falkTX/Cadence/blob/c167f35fbb76c4246c730b29262a59da73010412/src/systray.py#L104). I'm not sure if a [QSystemTrayIcon](https://doc.qt.io/qt-5/qsystemtrayicon.html) can have it.

This is how I cleaned the html code/rich text:
https://github.com/falkTX/Cadence/blob/a2e733abc9b6617fa00246334a1544e2795d1d1a/src/cadence.py#L1520
```python
        systrayText  = "Cadence\n "
        systrayText += "%s: %s\n" % (self.tr("JACK Status"), self.label_jack_status.text())
        systrayText += "%s: %s\n" % (self.tr("Realtime"), self.label_jack_realtime.text())
        systrayText += "%s: %s\n" % (self.tr("DSP Load"), self.label_jack_dsp.text())
        systrayText += "%s: %s\n" % (self.tr("Xruns"), self.label_jack_xruns.text())
        systrayText += "%s: %s\n" % (self.tr("Buffer Size"), self.label_jack_bfsize.text())
        systrayText += "%s: %s\n" % (self.tr("Sample Rate"), self.label_jack_srate.text())
        systrayText += "%s: %s" % (self.tr("Block Latency"), self.label_jack_latency.text())
```

**Comment by Joan31** [comment]
Same probleme on Arch Linux :+1: 

![image](https://user-images.githubusercontent.com/12939441/98830198-69ffb180-243a-11eb-83b1-e09970f0aa7a.png)

**Comment by realToadtoad** [comment]
It looks like KDE removed HTML parsing due to a security risk, so it seems like the tray indicator will have to switch to being plaintext.

Sources:
https://bugs.kde.org/show_bug.cgi?id=422616
https://invent.kde.org/frameworks/plasma-framework/-/merge_requests/6
