### ISSUE TITLE
failed to start jack when different user login in Manjaro KDE 21.1.2

### ISSUE THREAD

**Issue by rafidalhaque** [falkTX/Cadence#331]
When I login with a different user credential, and going to start jack with cadence. It shows me a error message that,

```
failed to start jack, please check the logs for more information.
```

**and the log is here:**
```
Sun Sep  5 13:43:45 2021: Starting jack server...
Sun Sep  5 13:43:45 2021: JACK server starting in realtime mode with priority 10
Sun Sep  5 13:43:45 2021: self-connect-mode is "Don't restrict self connect requests"
Sun Sep  5 13:43:45 2021: ERROR: Cannot lock down 107341340 byte memory area (Cannot allocate memory)
Sun Sep  5 13:43:45 2021: ERROR: Cannot open DB environment: Permission denied
Sun Sep  5 13:43:45 2021: Acquired audio card Audio0
Sun Sep  5 13:43:45 2021: creating alsa driver ... hw:PCH,0|hw:PCH,0|1024|2|48000|0|0|nomon|swmeter|-|32bit
Sun Sep  5 13:43:45 2021: ERROR: 

ATTENTION: The playback device "hw:PCH,0" is already in use. Please stop the application using it and run JACK again
Sun Sep  5 13:43:45 2021: ERROR: Cannot open DB environment: Permission denied
Sun Sep  5 13:43:45 2021: Released audio card Audio0
Sun Sep  5 13:43:45 2021: ERROR: Cannot initialize driver
Sun Sep  5 13:43:45 2021: ERROR: JackServer::Open failed with -1
Sun Sep  5 13:43:45 2021: ERROR: Failed to open server
```

### System information:

**OS:** Manjaro Linux x86_64 
**Host:** H310M S2H 2.0 
**Kernel:** 5.13.13-1-MANJARO
**CPU:** Intel i3-8100 (4) @ 3.600GHz 
**GPU:** Intel CoffeeLake-S GT2 [UHD Graphics 630] 

**How can i solve this problem, please?**

**Comment by falkTX** [comment]
This is not supported in Cadence, using jack with the same audio card for multiple users.
There is a special way to allow jack to work on such setups, but I never tried it myself and do not even know if it still works. If you need something to keep researching, this is called "promiscuous mode".
Still unsupported in Cadence though.
