### ISSUE TITLE
Unable to install on Ubuntu 22.04: Package 'Cadence' is virtual.

### ISSUE THREAD

**Issue by francoisromain** [falkTX/Cadence#350]
Hello, 
when I try to install Cadence on Ubuntu 22.04, I click on [the link: `apt://cadence`](apt://cadence) on [this page](https://kx.studio/Applications:Cadence), the choose `AptUrl` as the application to open the link. A popup shows up with the message : ` Package 'Cadence' is virtual.` and a `Close` button. 

How can I install Cadence on Ubuntu? 
Thank you

**Comment by falkTX** [comment]
build it from source or install from the kxstudio repositories.
cadence is not packaged in neither debian or ubuntu

**Comment by francoisromain** [comment]
Thank you for your answer. How do I install it from the kxstudio repositories please?

**Comment by falkTX** [comment]
Either enable the full repos as per https://kx.studio/Repositories or install individual deb files from https://kx.studio/Repositories:Applications

**Comment by francoisromain** [comment]
Ok thank you
