### ISSUE TITLE
cannot login after kxstudio/cadence update [04/18/2015]

### ISSUE THREAD

**Issue by distrozapper** [falkTX/Cadence#99]
This issue has been watched on debian jessie/XFCE and ubuntu 14.04/KDE:
Graphical login (via GUI) is impossible, login via (CTRL+ALT+F1) terminal works.
Selecting the "Default" session manager in the login GUI doesn't allow login. 

Known Workaround:
In the login GUI, look for a button to select the session manager. Click it and choose any valid session manager not named "Default". Try login again.

Happens/happened with cadence  1:0.8.1+git20150418.

In case you try to login with "Default" session manager and you fail, the (hidden) .xsession-errors file in your home folder might look like this:

Xsession: X session started for <user> at (date)
localuser:<user> being added to access control list
tryCloseJackDBus() failed
Traceback (most recent call last):
  File "/usr/share/cadence/src/cadence_session_start.py", line 221, in <module>
    sys.exit(startSession(True))
  File "/usr/share/cadence/src/cadence_session_start.py", line 54, in startSession
    DBus.bus  = dbus.SessionBus()
  File "/usr/lib/python3/dist-packages/dbus/_dbus.py", line 211, in __new__
    mainloop=mainloop)
  File "/usr/lib/python3/dist-packages/dbus/_dbus.py", line 100, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 122, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoServer: Failed to connect to socket /tmp/dbus-6bnkVIvd7A: Verbindungsaufbau abgelehnt

**Comment by falkTX** [comment]
Should be fixed now, please test.

**Comment by distrozapper** [comment]
cadence build 1:0.8.1+git20150418.2 Test OK, WORKSFORME :)
Autologin works, selecting session management "Default" works and allows login now.
Thank you very much falkTX!
From my side, this issue can be closed.
